'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Drink_Machine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _000145352() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("000145352", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _360_F_241372790_IaK4wwYRK0oOOOpX1m1sMnwHMyq7r1Z0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("360_F_241372790_IaK4wwYRK0oOOOpX1m1sMnwHMyq7r1Z0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5a214d4c_b0f7_4eb5_b014_4be4ee70a0ec_1_fa15401fb1e92228dc963f0535d4278c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5a214d4c-b0f7-4eb5-b014-4be4ee70a0ec_1.fa15401fb1e92228dc963f0535d4278c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6e7918e2_2615_4cc0_bd0d_7e2dedb292bc_c96162b9bf031cc0cb3ed24e2f76961e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6e7918e2-2615-4cc0-bd0d-7e2dedb292bc.c96162b9bf031cc0cb3ed24e2f76961e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _96bf350a_5293_4fb0_b280_4b99d0cc3736_b6b7824e05568773147099b84e0c19e6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("96bf350a-5293-4fb0-b280-4b99d0cc3736.b6b7824e05568773147099b84e0c19e6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attachment_108654470() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachment_108654470", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cb4c9f0b_a402_4b63_afb9_efdbdfd72450_450d53103f6484ee1ab57a6c8e665ea4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cb4c9f0b-a402-4b63-afb9-efdbdfd72450.450d53103f6484ee1ab57a6c8e665ea4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diet_dr_pepper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diet dr pepper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dr_pepper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dr pepper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vector_logo_vending_machine_food_drinks_vector_logo_vending_machine_food_170618978() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vector-logo-vending-machine-food-drinks-vector-logo-vending-machine-food-17061897"& _ 
                        "8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
